# Generated by Django 4.0.10 on 2025-06-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
